Repository Overload-Technologies/Overload, pull requests merged in 2020-05, with the labels that each got.

#73 Updating Sol2 version and fixing bigobj issue
  Dependencies/lua/include/sol.hpp
  Sources/Overload/OvCore/OvCore.vcxproj
Labels: Bug

#74 Exposing frustum culling to Lua and fixing frustum debugging issue
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaComponentBinder.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
Labels: Bug, Feature

#76 Force using dedicated GPU
  Sources/Overload/OvEditor/src/OvEditor/Main.cpp
  Sources/Overload/OvGame/src/OvGame/Main.cpp
  Sources/Overload/OvRendering/OvRendering.vcxproj
  Sources/Overload/OvRendering/OvRendering.vcxproj.filters
  Sources/Overload/OvRendering/include/OvRendering/Utils/Defines.h
Labels: Crash
