Repository Overload-Technologies/Overload, pull requests merged in 2020-07, with the labels that each got.

#123 Updating editor style
  Sources/Overload/OvEditor/layout.ini
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/ProjectHub.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Toolbar.cpp
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
  Sources/Overload/OvUI/include/OvUI/Core/UIManager.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imconfig.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imgui.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imgui_internal.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_rectpack.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_textedit.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_truetype.h
  Sources/Overload/OvUI/include/OvUI/Panels/PanelWindow.h
  Sources/Overload/OvUI/include/OvUI/Settings/PanelWindowSettings.h
  Sources/Overload/OvUI/include/OvUI/Styling/EStyle.h
  Sources/Overload/OvUI/src/OvUI/Core/UIManager.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_demo.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_draw.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_impl_glfw.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_widgets.cpp
  Sources/Overload/OvUI/src/OvUI/Modules/Canvas.cpp
  Sources/Overload/OvUI/src/OvUI/Panels/PanelWindow.cpp
Labels: Editor, Feature, Refactoring

#120 Fixing layout reset and updating ImGui to 1.77 WIP
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvUI/include/OvUI/Core/UIManager.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imconfig.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imgui.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imgui_internal.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_rectpack.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_textedit.h
  Sources/Overload/OvUI/include/OvUI/ImGui/imstb_truetype.h
  Sources/Overload/OvUI/src/OvUI/Core/UIManager.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_demo.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_draw.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_impl_glfw.cpp
  Sources/Overload/OvUI/src/OvUI/ImGui/imgui_widgets.cpp
  Sources/Overload/OvUI/src/OvUI/Modules/Canvas.cpp
Labels: Bug, Refactoring

#127 Disable client-side decorations for project hub window.
  Sources/Overload/OvEditor/src/OvEditor/Core/ProjectHub.cpp
  Sources/Overload/OvUI/include/OvUI/Panels/PanelWindow.h
  Sources/Overload/OvUI/include/OvUI/Settings/PanelWindowSettings.h
  Sources/Overload/OvUI/src/OvUI/Panels/PanelWindow.cpp
Labels: Feature, QoL
