Repository Overload-Technologies/Overload, pull requests merged in 2020-06, with the labels that each got.

#79 Reversing the order of entries in profiler reports
  Sources/Overload/OvAnalytics/src/OvAnalytics/Profiling/Profiler.cpp
Labels: Editor, QoL

#83 Editor crashes when deleting an already deleted file/folder
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
Labels: Bug, Crash, Editor

#93 Making `OvMaths::FQuaternion::Identity` a constant instead of a static method
  Sources/Overload/OvCore/include/OvCore/ECS/Components/CTransform.h
  Sources/Overload/OvMaths/include/OvMaths/FQuaternion.h
  Sources/Overload/OvMaths/include/OvMaths/FTransform.h
  Sources/Overload/OvMaths/src/OvMaths/FQuaternion.cpp
Labels: Refactoring

#96 Fixing TextureID typo (d renamed to id)
  Sources/Overload/OvCore/src/OvCore/Helpers/GUIDrawer.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvUI/include/OvUI/Internal/TextureID.h
Labels: Bug

#99 Improving the actor duplication naming system
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
Labels: Editor, Feature, QoL

#100 Removing useless transform parameter from Camera constructor
  Sources/Overload/OvRendering/include/OvRendering/LowRenderer/Camera.h
  Sources/Overload/OvRendering/src/OvRendering/LowRenderer/Camera.cpp
Labels: Refactoring

#102 Adding orthographic camera mode
  Sources/Overload/OvCore/include/OvCore/ECS/Components/CCamera.h
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CCamera.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaComponentBinder.cpp
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorRenderer.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorRenderer.cpp
  Sources/Overload/OvMaths/include/OvMaths/FMatrix4.h
  Sources/Overload/OvMaths/src/OvMaths/FMatrix4.cpp
  Sources/Overload/OvRendering/OvRendering.vcxproj
  Sources/Overload/OvRendering/OvRendering.vcxproj.filters
  Sources/Overload/OvRendering/include/OvRendering/LowRenderer/Camera.h
  Sources/Overload/OvRendering/include/OvRendering/Settings/EProjectionMode.h
  Sources/Overload/OvRendering/src/OvRendering/LowRenderer/Camera.cpp
Labels: Feature, Graphics

#118 README update with Emphasis onto Wiki, Discord and Contributing
  README.md
Labels: Documentation
