Repository Overload-Technologies/Overload, pull requests merged in 2020-11, with the labels that each got.

#178 Updating Overload shader versions from 460 to 430
  Resources/Engine/Shaders/Lambert.glsl
  Resources/Engine/Shaders/Standard.glsl
  Resources/Engine/Shaders/StandardPBR.glsl
  Resources/Engine/Shaders/Unlit.glsl
  Sources/Overload/OvEditor/src/OvEditor/Resources/RawShaders.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/ShapeDrawer.cpp
Labels: Bug, Refactoring

#180 Re-adding "Updating Overload shader versions from 460 to 430" after fixing the issue
  Resources/Engine/Shaders/Lambert.glsl
  Resources/Engine/Shaders/Standard.glsl
  Resources/Engine/Shaders/StandardPBR.glsl
  Resources/Engine/Shaders/Unlit.glsl
  Sources/Overload/OvEditor/src/OvEditor/Resources/RawShaders.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/ShapeDrawer.cpp
Labels: Bug, Graphics, Refactoring

#181 Adding requirements to Overload's README.md
  README.md
Labels: Documentation

#176 Increasing camera default move speed
  Sources/Overload/OvEditor/include/OvEditor/Core/CameraController.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
Labels: Editor, QoL

#183 Replacing glGetnUniform by glGetUniform
  Sources/Overload/OvRendering/src/OvRendering/Resources/Shader.cpp
Labels: Bug, Graphics

#184 Add virtual destructor on ISerializable and override ~Actor()
  Sources/Overload/OvCore/include/OvCore/API/ISerializable.h
  Sources/Overload/OvCore/include/OvCore/ECS/Actor.h
Labels: Bug, Good First Issue
