Repository Overload-Technologies/Overload, pull requests merged in 2020-10, with the labels that each got.

#150 Hierarchy actor focus on double click
  Sources/Overload/OvEditor/src/OvEditor/Panels/Hierarchy.cpp
  Sources/Overload/OvUI/include/OvUI/Widgets/Layout/TreeNode.h
  Sources/Overload/OvUI/include/OvUI/Widgets/Texts/TextClickable.h
  Sources/Overload/OvUI/src/OvUI/Widgets/Layout/TreeNode.cpp
  Sources/Overload/OvUI/src/OvUI/Widgets/Texts/TextClickable.cpp
Labels: Editor, Feature, QoL

#153 Adding validation to the add script button
  Sources/Overload/OvEditor/include/OvEditor/Panels/Inspector.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
Labels: Bug, QoL

#158 Adding null-check to inspector actor unfocus
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
Labels: Bug, Crash, Editor

#160 Fixing TreeNode requiring a double click to get expanded
  Sources/Overload/OvUI/src/OvUI/Widgets/Layout/TreeNode.cpp
Labels: Bug, Critical, Editor

#84 Window scroll control and console log order
  Sources/Overload/OvEditor/src/OvEditor/Panels/Console.cpp
  Sources/Overload/OvUI/include/OvUI/Internal/WidgetContainer.h
  Sources/Overload/OvUI/include/OvUI/Panels/PanelWindow.h
  Sources/Overload/OvUI/src/OvUI/Internal/WidgetContainer.cpp
  Sources/Overload/OvUI/src/OvUI/Panels/PanelWindow.cpp
Labels: Editor, Feature, QoL

#162 Improved actor creation menu
  Sources/Overload/OvEditor/OvEditor.vcxproj
  Sources/Overload/OvEditor/OvEditor.vcxproj.filters
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorActions.h
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorActions.inl
  Sources/Overload/OvEditor/include/OvEditor/Utils/ActorCreationMenu.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Hierarchy.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
  Sources/Overload/OvEditor/src/OvEditor/Utils/ActorCreationMenu.cpp
Labels: Editor, Feature, QoL, Refactoring

#164 Improved grid and view backgrounds
  Sources/Overload/OvEditor/include/OvEditor/Panels/AView.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorRenderer.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Resources/RawShaders.cpp
Labels: Bug, Editor, QoL, Refactoring

#167 Changing default ambient light settings
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CAmbientBoxLight.cpp
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CAmbientSphereLight.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
Labels: QoL

#169 Now ignoring .vscode folder in .gitignore
  .gitignore
Labels: Project Configuration, QoL

#170 Refactor service locator
  Sources/Overload/OvCore/OvCore.vcxproj
  Sources/Overload/OvCore/OvCore.vcxproj.filters
  Sources/Overload/OvCore/include/OvCore/Global/ServiceLocator.h
  Sources/Overload/OvCore/include/OvCore/Global/ServiceLocator.inl
  Sources/Overload/OvCore/src/OvCore/Global/ServiceLocator.cpp
  Sources/Overload/OvDebug/OvDebug.vcxproj
  Sources/Overload/OvDebug/OvDebug.vcxproj.filters
  Sources/Overload/OvDebug/include/OvDebug/Utils/Assertion.h
  Sources/Overload/OvDebug/src/OvDebug/Utils/Assertion.cpp
Labels: Optimization, Refactoring

#171 Fixing OpenGL buffer cleanup.
  Sources/Overload/OvRendering/src/OvRendering/Buffers/Framebuffer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Buffers/ShaderStorageBuffer.cpp
Labels: Bug

#173 Increased editor camera sensitivity
  Sources/Overload/OvEditor/include/OvEditor/Core/CameraController.h
Labels: Editor, QoL

#175 Revert "Refactor service locator"
  Sources/Overload/OvCore/OvCore.vcxproj
  Sources/Overload/OvCore/OvCore.vcxproj.filters
  Sources/Overload/OvCore/include/OvCore/Global/ServiceLocator.h
  Sources/Overload/OvCore/include/OvCore/Global/ServiceLocator.inl
  Sources/Overload/OvCore/src/OvCore/Global/ServiceLocator.cpp
  Sources/Overload/OvDebug/OvDebug.vcxproj
  Sources/Overload/OvDebug/OvDebug.vcxproj.filters
  Sources/Overload/OvDebug/include/OvDebug/Utils/Assertion.h
  Sources/Overload/OvDebug/src/OvDebug/Utils/Assertion.cpp
Labels: Bug, Critical
