Repository Overload-Technologies/Overload, pull requests merged in 2020-09, with the labels that each got.

#131 Remove GL calls from anywhere else than OvRendering
  Sources/Overload/OvEditor/src/OvEditor/Panels/AView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
  Sources/Overload/OvRendering/OvRendering.vcxproj
  Sources/Overload/OvRendering/OvRendering.vcxproj.filters
  Sources/Overload/OvRendering/include/OvRendering/Core/Renderer.h
  Sources/Overload/OvRendering/include/OvRendering/Settings/EPixelDataFormat.h
  Sources/Overload/OvRendering/include/OvRendering/Settings/EPixelDataType.h
  Sources/Overload/OvRendering/src/OvRendering/Core/Renderer.cpp
Labels: Graphics, Refactoring

#138 Forcing post-build to get triggered when building
  Sources/Overload/OvAnalytics/OvAnalytics.vcxproj
  Sources/Overload/OvAudio/OvAudio.vcxproj
  Sources/Overload/OvCore/OvCore.vcxproj
  Sources/Overload/OvDebug/OvDebug.vcxproj
  Sources/Overload/OvEditor/OvEditor.vcxproj
  Sources/Overload/OvGame/OvGame.vcxproj
  Sources/Overload/OvMaths/OvMaths.vcxproj
  Sources/Overload/OvPhysics/OvPhysics.vcxproj
  Sources/Overload/OvRendering/OvRendering.vcxproj
  Sources/Overload/OvTools/OvTools.vcxproj
  Sources/Overload/OvUI/OvUI.vcxproj
  Sources/Overload/OvWindowing/OvWindowing.vcxproj
Labels: Project Configuration, QoL

#119 Unique string generation system
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvTools/include/OvTools/Utils/String.h
  Sources/Overload/OvTools/src/OvTools/Utils/String.cpp
Labels: Editor, Feature, QoL, Refactoring

#137 Fixing un-usable alpha-numeric keys (0 to 9)
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaGlobalsBinder.cpp
Labels: Bug, Critical

#125 Updating the help menu
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
Labels: Documentation, Editor, QoL, Refactoring

#126 Improving the AssetProperties window (Previously AssetMetadataEditor)
  Sources/Overload/OvCore/include/OvCore/Helpers/GUIDrawer.h
  Sources/Overload/OvCore/src/OvCore/Helpers/GUIDrawer.cpp
  Sources/Overload/OvEditor/OvEditor.vcxproj
  Sources/Overload/OvEditor/OvEditor.vcxproj.filters
  Sources/Overload/OvEditor/include/OvEditor/Panels/AssetProperties.h
  Sources/Overload/OvEditor/src/OvEditor/Core/Editor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetMetadataEditor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetProperties.cpp
  Sources/Overload/OvTools/OvTools.vcxproj
  Sources/Overload/OvTools/OvTools.vcxproj.filters
  Sources/Overload/OvTools/include/OvTools/Utils/SizeConverter.h
  Sources/Overload/OvTools/src/OvTools/Utils/SizeConverter.cpp
Labels: Editor, Feature

#135 Updating the README.md for 1.3.0
  README.md
  Showcase/Advanced_Lighting.jpg
  Showcase/Custom_Shaders.jpg
  Showcase/Masthead.jpg
  Showcase/Material_Editor.jpg
  Showcase/PBR_Shading.jpg
  Showcase/Scene_Edition.jpg
  Showcase/Standard_Shaders.jpg
  Showcase/logo.png
Labels: Documentation

#141 Fixing VS2019 MSVC16.7 no_except bug with sol2
  Dependencies/lua/include/sol.hpp
Labels: Bug, Critical

#149 Updating editor default layout
  Sources/Overload/OvEditor/layout.ini
Labels: Bug, Editor
