Repository Overload-Technologies/Overload, pull requests merged in 2025-02, with the labels that each got.

#315 Added shadow mapping for directional lights
  README.md
  Resources/Engine/Materials/Default.ovmat
  Resources/Engine/Shaders/Lighting/BlinnPhong.ovfxh
  Resources/Engine/Shaders/Lighting/PBR.ovfxh
  Resources/Engine/Shaders/Lighting/Shared.ovfxh
  Resources/Engine/Shaders/Shadow.ovfx
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Sources/Overload/OvCore/include/OvCore/ECS/Components/CDirectionalLight.h
  Sources/Overload/OvCore/include/OvCore/ECS/Components/CLight.h
  Sources/Overload/OvCore/include/OvCore/Helpers/Serializer.h
  Sources/Overload/OvCore/include/OvCore/Rendering/EngineBufferRenderFeature.h
  Sources/Overload/OvCore/include/OvCore/Rendering/ShadowRenderFeature.h
  Sources/Overload/OvCore/include/OvCore/Rendering/ShadowRenderPass.h
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CDirectionalLight.cpp
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CLight.cpp
  Sources/Overload/OvCore/src/OvCore/Helpers/Serializer.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/EngineBufferRenderFeature.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/SceneRenderer.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderFeature.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderPass.cpp
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaComponentBinder.cpp
  Sources/Overload/OvEditor/premake5.lua
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MaterialEditor.cpp
  Sources/Overload/OvGame/premake5.lua
  Sources/Overload/OvRendering/include/OvRendering/Buffers/Framebuffer.h
  Sources/Overload/OvRendering/include/OvRendering/Core/ABaseRenderer.h
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.h
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.inl
  Sources/Overload/OvRendering/include/OvRendering/Entities/Light.h
  Sources/Overload/OvRendering/include/OvRendering/Features/DebugShapeRenderFeature.h
  Sources/Overload/OvRendering/include/OvRendering/Features/LightingRenderFeature.h
  Sources/Overload/OvRendering/include/OvRendering/Resources/Texture.h
  Sources/Overload/OvRendering/include/OvRendering/Settings/ERenderPassOrder.h
  Sources/Overload/OvRendering/src/OvRendering/Buffers/Framebuffer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
  Sources/Overload/OvRendering/src/OvRendering/Entities/Light.cpp
  Sources/Overload/OvRendering/src/OvRendering/Features/DebugShapeRenderFeature.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Shader.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Texture.cpp
Labels: Feature, Graphics

#334 Fixed editor view rendering to properly skip drawing a view if it's not visible
  Sources/Overload/OvEditor/src/OvEditor/Core/Editor.cpp
  Sources/Overload/OvUI/include/OvUI/Panels/PanelWindow.h
  Sources/Overload/OvUI/src/OvUI/Panels/PanelWindow.cpp
Labels: QoL, Optimization, Graphics

#324 Added proper support for collapsing to `GroupCollapsable`, and set default to not collapsed
  Sources/Overload/OvUI/include/OvUI/Widgets/Layout/GroupCollapsable.h
  Sources/Overload/OvUI/src/OvUI/Widgets/Layout/GroupCollapsable.cpp
Labels: QoL, Feature, Editor

#327 Fixed frustum culling debugger (and re-enabled frustum light culling)
  Sources/Overload/OvCore/include/OvCore/Rendering/SceneRenderer.h
  Sources/Overload/OvCore/src/OvCore/Rendering/SceneRenderer.cpp
  Sources/Overload/OvEditor/include/OvEditor/Settings/EditorSettings.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/AView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AViewControllable.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
  Sources/Overload/OvRendering/include/OvRendering/Features/LightingRenderFeature.h
  Sources/Overload/OvRendering/src/OvRendering/Features/LightingRenderFeature.cpp
Labels: Bug, Feature, Editor, Optimization

#326 Fixed OvGame build folder generation
  Sources/Overload/OvEditor/premake5.lua
  Sources/Overload/OvGame/premake5.lua
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
  Sources/Overload/OvGame/src/OvGame/Core/Game.cpp
  Sources/Overload/OvTools/include/OvTools/Filesystem/IniFile.h
  Sources/Overload/OvTools/include/OvTools/Filesystem/IniFile.inl
  Sources/Overload/OvWindowing/include/OvWindowing/Settings/WindowSettings.h
Labels: Bug, Critical, Project Configuration

#330 Added post-process effects
  Resources/Engine/Shaders/Lighting/PBR.ovfxh
  Resources/Engine/Shaders/PostProcess/ApplyExposure.ovfx
  Resources/Engine/Shaders/PostProcess/AutoExposure.ovfx
  Resources/Engine/Shaders/PostProcess/Blit.ovfx
  Resources/Engine/Shaders/PostProcess/Bloom.ovfx
  Resources/Engine/Shaders/PostProcess/Blur.ovfx
  Resources/Engine/Shaders/PostProcess/Brightness.ovfx
  Resources/Engine/Shaders/PostProcess/FXAA.ovfx
  Resources/Engine/Shaders/PostProcess/Luminance.ovfx
  Resources/Engine/Shaders/PostProcess/Tonemapping.ovfx
  Sources/Overload/OvCore/include/OvCore/ECS/Components/CPostProcessStack.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/AEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/AutoExposureEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/BloomEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/FXAAEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/PostProcessStack.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/PostProcessStack.inl
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/TonemappingEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcessRenderPass.h
  Sources/Overload/OvCore/include/OvCore/Rendering/SceneRenderer.h
  Sources/Overload/OvCore/include/OvCore/SceneSystem/Scene.h
  Sources/Overload/OvCore/src/OvCore/ECS/Actor.cpp
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CPostProcessStack.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/APostProcessEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/AutoExposureEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/BloomEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/FXAAEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/PostProcessStack.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/TonemappingEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcessRenderPass.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/SceneRenderer.cpp
  Sources/Overload/OvCore/src/OvCore/SceneSystem/Scene.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaActorBinder.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaComponentBinder.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/DebugSceneRenderer.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/GridRenderPass.cpp
  Sources/Overload/OvEditor/src/OvEditor/Utils/ActorCreationMenu.cpp
  Sources/Overload/OvRendering/include/OvRendering/Buffers/Framebuffer.h
  Sources/Overload/OvRendering/include/OvRendering/Core/ABaseRenderer.h
  Sources/Overload/OvRendering/include/OvRendering/Entities/Drawable.h
  Sources/Overload/OvRendering/include/OvRendering/Settings/EBlitFlags.h
  Sources/Overload/OvRendering/src/OvRendering/Buffers/Framebuffer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/CompositeRenderer.cpp
Labels: Feature, Graphics

#349 Fixed documentation inconsistencies
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaComponentBinder.cpp
Labels: Documentation, QoL

#350 Enable Frustum Culling by default
  Sources/Overload/OvEditor/include/OvEditor/Settings/EditorSettings.h
  Sources/Overload/OvRendering/src/OvRendering/Entities/Camera.cpp
Labels: QoL, Editor, Graphics

#338 Fix OvGame not rendering properly
  Sources/Overload/OvGame/include/OvGame/Core/Context.h
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
  Sources/Overload/OvGame/src/OvGame/Core/Game.cpp
  Sources/Overload/OvRendering/include/OvRendering/Buffers/Framebuffer.h
  Sources/Overload/OvRendering/src/OvRendering/Buffers/Framebuffer.cpp
Labels: Bug, Critical, Graphics

#311 Updating C++ Version from C++17 to C++20
  Sources/Overload/OvAnalytics/premake5.lua
  Sources/Overload/OvAudio/premake5.lua
  Sources/Overload/OvCore/premake5.lua
  Sources/Overload/OvDebug/premake5.lua
  Sources/Overload/OvEditor/premake5.lua
  Sources/Overload/OvGame/premake5.lua
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
  Sources/Overload/OvMaths/premake5.lua
  Sources/Overload/OvPhysics/premake5.lua
  Sources/Overload/OvRendering/premake5.lua
  Sources/Overload/OvTools/include/OvTools/Utils/ReferenceOrValue.h
  Sources/Overload/OvTools/premake5.lua
  Sources/Overload/OvUI/premake5.lua
  Sources/Overload/OvWindowing/premake5.lua
Labels: Optimization, Project Configuration

#357 Fixed clear color alpha was set to 0.0f
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
Labels: Bug, Graphics

#365 Added utility scripts & VERSION.txt file
  .gitignore
  GenerateProjects.bat
  OpenInVisualStudio.bat
  Scripts/GenerateProjects.bat
  Scripts/MSVC/BuildAll.bat
  Scripts/MSVC/MakeReleaseBuild.bat
  Scripts/MSVC/OpenSolution.bat
  Scripts/RunEditor.bat
  Sources/Overload/OvEditor/premake5.lua
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
  VERSION.txt
Labels: QoL, Project Configuration

#360 Added GetPathToAppdata util function and removed getenv() usage
  Sources/Overload/OvDebug/src/OvDebug/FileHandler.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/ProjectHub.cpp
  Sources/Overload/OvTools/include/OvTools/Utils/SystemCalls.h
  Sources/Overload/OvTools/src/OvTools/Utils/SystemCalls.cpp
Labels: Refactoring

#366 Fixed appdata path containing the null terminator character
  Sources/Overload/OvTools/src/OvTools/Utils/SystemCalls.cpp
Labels: Bug, Critical

#364 Updated README to show important information first
  README.md
Labels: Documentation

#367 Updated branch in CONTRIBUTING.md from develop to main
  CONTRIBUTING.md
Labels: Documentation

#329 Added serialization (ini) of editor settings
  Sources/Overload/OvEditor/include/OvEditor/Settings/EditorSettings.h
  Sources/Overload/OvEditor/src/OvEditor/Core/Editor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Settings/EditorSettings.cpp
Labels: QoL, Feature, Editor

#369 Fixed invalid default scene when created through the asset browser
  Sources/Overload/OvCore/include/OvCore/SceneSystem/Scene.h
  Sources/Overload/OvCore/include/OvCore/SceneSystem/SceneManager.h
  Sources/Overload/OvCore/src/OvCore/SceneSystem/Scene.cpp
  Sources/Overload/OvCore/src/OvCore/SceneSystem/SceneManager.cpp
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorActions.h
  Sources/Overload/OvEditor/src/OvEditor/Core/Editor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
Labels: Bug, Critical

#372 Added function to trim leading/trailing whitespaces
  Sources/Overload/OvTools/include/OvTools/Utils/String.h
  Sources/Overload/OvTools/src/OvTools/Filesystem/IniFile.cpp
  Sources/Overload/OvTools/src/OvTools/Utils/String.cpp
Labels: Bug, Critical, Crash, Good First Issue

#328 Added dynamic editor window size selection
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvWindowing/include/OvWindowing/Context/Device.h
  Sources/Overload/OvWindowing/include/OvWindowing/Settings/WindowSettings.h
  Sources/Overload/OvWindowing/src/OvWindowing/Context/Device.cpp
  Sources/Overload/OvWindowing/src/OvWindowing/Window.cpp
Labels: QoL, Editor

#376 Fixed scene not properly deleted
  Sources/Overload/OvCore/src/OvCore/SceneSystem/SceneManager.cpp
Labels: Bug, Critical, Crash

#355 Reworked the scripting system to be fully agnostic
  Sources/Overload/OvCore/include/OvCore/ECS/Components/Behaviour.h
  Sources/Overload/OvCore/include/OvCore/ECS/Components/Behaviour.inl
  Sources/Overload/OvCore/include/OvCore/Scripting/Common/EScriptingLanguage.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Common/TScript.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Common/TScriptEngine.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Lua/LuaScript.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Lua/LuaScriptEngine.h
  Sources/Overload/OvCore/include/OvCore/Scripting/LuaActorBinder.h
  Sources/Overload/OvCore/include/OvCore/Scripting/LuaBinder.h
  Sources/Overload/OvCore/include/OvCore/Scripting/LuaComponentBinder.h
  Sources/Overload/OvCore/include/OvCore/Scripting/LuaGlobalsBinder.h
  Sources/Overload/OvCore/include/OvCore/Scripting/LuaMathsBinder.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Null/NullScript.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Null/NullScriptEngine.h
  Sources/Overload/OvCore/include/OvCore/Scripting/ScriptEngine.h
  Sources/Overload/OvCore/include/OvCore/Scripting/ScriptInterpreter.h
  Sources/Overload/OvCore/src/OvCore/ECS/Components/Behaviour.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/Bindings/LuaActorBindings.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/Bindings/LuaComponentsBindings.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/Bindings/LuaGlobalBindings.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/Bindings/LuaMathBindings.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/LuaScript.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/LuaScriptEngine.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaBinder.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/LuaGlobalsBinder.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Null/NullScript.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Null/NullScriptEngine.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/ScriptInterpreter.cpp
  Sources/Overload/OvEditor/include/OvEditor/Core/Context.h
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
  Sources/Overload/OvGame/include/OvGame/Core/Context.h
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
  Sources/Overload/OvMaths/src/OvMaths/FVector3.cpp
  Sources/Overload/OvTools/src/OvTools/Utils/PathParser.cpp
  Sources/Overload/premake5.lua
Labels: QoL, Feature, Refactoring

#377 Fixed compilation warnings
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Settings/EditorSettings.cpp
  Sources/Overload/OvRendering/include/OvRendering/Core/CompositeRenderer.inl
Labels: Cleanup

#393 Moved repo refs from `adriengivry` to `Overload-Technologies`
  README.md
  Sources/Overload/OvEditor/src/OvEditor/Panels/MenuBar.cpp
Labels: Documentation
