Repository Overload-Technologies/Overload, pull requests merged in 2025-05, with the labels that each got.

#477 Fixed Asset View when editing material (#474)
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
Labels: Editor

#481 Added back hierarchy search bar
  Sources/Overload/OvEditor/include/OvEditor/Panels/Hierarchy.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/Hierarchy.cpp
Labels: Editor

#470 Exposed shader feature set to the material editor
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
  Sources/Overload/OvEditor/include/OvEditor/Panels/MaterialEditor.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/MaterialEditor.cpp
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.h
  Sources/Overload/OvRendering/include/OvRendering/Entities/Drawable.h
  Sources/Overload/OvRendering/include/OvRendering/Resources/Shader.h
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Shader.cpp
Labels: Editor, Graphics

#484 Materials can now be dropped onto an actor
  Sources/Overload/OvEditor/include/OvEditor/Panels/SceneView.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
Labels: QoL, Editor

#475 Added PR template and updated issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Documentation

#478 Added the ability to create custom shadow passes
  Resources/Engine/Shaders/Lambert.ovfx
  Resources/Engine/Shaders/ShadowFallback.ovfx
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Resources/Engine/Shaders/Unlit.ovfx
  Sources/Overload/OvCore/include/OvCore/Rendering/ShadowRenderPass.h
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderFeature.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderPass.cpp
Labels: Graphics

#482 Updated OvWindowing so it has the last say on the cursor shape
  Sources/Overload/OvWindowing/include/OvWindowing/Window.h
  Sources/Overload/OvWindowing/src/OvWindowing/Window.cpp
Labels: Editor

#490 Added support for HDR textures
  Sources/Overload/OvCore/src/OvCore/ResourceManagement/TextureManager.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvRendering/include/OvRendering/Resources/Loaders/TextureLoader.h
  Sources/Overload/OvRendering/src/OvRendering/Resources/Loaders/TextureLoader.cpp
  Sources/Overload/OvTools/include/OvTools/Filesystem/IniFile.h
  Sources/Overload/OvTools/include/OvTools/Filesystem/IniFile.inl
  Sources/Overload/OvTools/src/OvTools/Utils/PathParser.cpp
Labels: Graphics

#491 Updated default camera settings to more appropriate values
  Sources/Overload/OvRendering/src/OvRendering/Entities/Camera.cpp
Labels: QoL, Editor

#492 Neater unit quad: no heap allocation
  Sources/Overload/OvRendering/include/OvRendering/Core/ABaseRenderer.h
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
Labels: Optimization, Cleanup

#495 Fixed the "Compile All Shaders" button
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Loaders/ShaderLoader.cpp
Labels: Editor

#497 Disabled frustum culling in asset view
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetView.cpp
Labels: Editor

#499 Updated README.md
  README.md
Labels: Documentation

#498 Updated coding conventions
  CONTRIBUTING.md
Labels: Documentation

#505 Fixed broken layout on resize (especially the toolbar)
  Sources/Overload/OvEditor/layout.ini
Labels: QoL, Editor

#506 Fixed disabled buttons not really disabled
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
  Sources/Overload/OvUI/src/OvUI/Widgets/Buttons/Button.cpp
  Sources/Overload/OvUI/src/OvUI/Widgets/Buttons/ButtonImage.cpp
Labels: Editor

#493 Added buttons to select gizmo operations from the toolbar
  Resources/Editor/Textures/Move.png
  Resources/Editor/Textures/Rotate.png
  Resources/Editor/Textures/Scale.png
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorActions.h
  Sources/Overload/OvEditor/include/OvEditor/Panels/SceneView.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorResources.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Toolbar.cpp
Labels: QoL, Editor

#507 Fixed layout was still broken
  Sources/Overload/OvEditor/layout.ini
Labels: Editor

#508 Added support for custom picking pass
  Resources/Editor/Shaders/PickingFallback.ovfx
  Sources/Overload/OvEditor/include/OvEditor/Rendering/PickingRenderPass.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorResources.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
Labels: Editor

#509 Added support for custom outline pass
  Resources/Editor/Shaders/OutlineFallback.ovfx
  Sources/Overload/OvEditor/include/OvEditor/Rendering/OutlineRenderFeature.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorResources.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/OutlineRenderFeature.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
Labels: Editor

#510 Cleanup standard shaders
  Resources/Engine/Shaders/Common/Utils.ovfxh
  Resources/Engine/Shaders/Lambert.ovfx
  Resources/Engine/Shaders/Lighting/BlinnPhong.ovfxh
  Resources/Engine/Shaders/Lighting/PBR.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Resources/Engine/Shaders/Unlit.ovfx
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
  Sources/Overload/OvRendering/src/OvRendering/HAL/OpenGL/GLShaderProgram.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Parsers/AssimpParser.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Shader.cpp
Labels: Graphics, Cleanup

#516 Fixed parallax mapping broken with non-flat models
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
Labels: Graphics

#519 Updated material editor to only show relevant shader settings
  Resources/Engine/Materials/Default.ovmat
  Resources/Engine/Shaders/Atmosphere.ovfx
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderFeature.cpp
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
  Sources/Overload/OvEditor/include/OvEditor/Panels/MaterialEditor.h
  Sources/Overload/OvEditor/src/OvEditor/Panels/MaterialEditor.cpp
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.h
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
Labels: Editor, Graphics

#522 Updated atmoshperic scattering implementation to also track directional light intensity
  Resources/Engine/Materials/Atmosphere.ovmat
  Resources/Engine/Shaders/Atmosphere.ovfx
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
Labels: Graphics

#526 Fixed parallax, atmosphere, and skysphere issues with ortho camera
  Resources/Engine/Materials/Atmosphere.ovmat
  Resources/Engine/Materials/Default.ovmat
  Resources/Engine/Materials/Skysphere.ovmat
  Resources/Engine/Shaders/Common/Utils.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MaterialEditor.cpp
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.h
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
Labels: Graphics

#529 Fixed crash with parallax mapping when an object is scaled to 0
  Resources/Engine/Shaders/Common/Utils.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
Labels: Crash, Graphics

#530 Exposed texture wrap and added support for parallax offset/tiling
  Resources/Engine/Shaders/Common/Utils.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Sources/Overload/OvCore/src/OvCore/ResourceManagement/TextureManager.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorResources.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetProperties.cpp
  Sources/Overload/OvRendering/include/OvRendering/Resources/Loaders/TextureLoader.h
  Sources/Overload/OvRendering/src/OvRendering/Resources/Loaders/TextureLoader.cpp
Labels: Graphics

#531 Added distance fade and alpha dithering
  Resources/Engine/Shaders/Common/Utils.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Sources/Overload/OvRendering/src/OvRendering/Resources/Loaders/ShaderLoader.cpp
Labels: Graphics

#532 Fixed broken gizmo depth test for picking
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
Labels: Critical, Graphics

#533 Added `IsDrawable` method to properly skip invalid draw calls
  Sources/Overload/OvRendering/include/OvRendering/Core/ABaseRenderer.h
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Core/CompositeRenderer.cpp
Labels: Graphics

#535 Fixed material deserialize didn't reset properties and features properly
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
Labels: Editor, Graphics

#536 Added support for gloss/spec PBR workflow
  Resources/Engine/Shaders/Lighting/PBR.ovfxh
  Resources/Engine/Shaders/StandardPBR.ovfx
Labels: QoL, Graphics

#538 StandardPBR is now Standard ->no more blinn-phong/lambert
  Resources/Editor/Models/Camera.fbx
  Resources/Engine/Materials/Default.ovmat
  Resources/Engine/Shaders/Lambert.ovfx
  Resources/Engine/Shaders/Lighting/BlinnPhong.ovfxh
  Resources/Engine/Shaders/Lighting/Lambert.ovfxh
  Resources/Engine/Shaders/Lighting/PBR.ovfxh
  Resources/Engine/Shaders/Lighting/Shadow.ovfxh
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/StandardPBR.ovfx
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/DebugSceneRenderer.cpp
  Sources/Overload/OvRendering/include/OvRendering/Features/LightingRenderFeature.h
  Sources/Overload/OvRendering/src/OvRendering/Features/LightingRenderFeature.cpp
Labels: Graphics

#541 Added additional CPU/GPU markers for Tracy profiler
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/AutoExposureEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/BloomEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/FXAAEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/TonemappingEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderPass.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/DebugSceneRenderer.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/GridRenderPass.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
Labels: Graphics

#542 Fixed incorrect blit viewport size
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
Labels: Critical, Graphics

#544 Added a pass system to shaders
  Resources/Engine/Shaders/Atmosphere.ovfx
  Resources/Engine/Shaders/Skysphere.ovfx
  Resources/Engine/Shaders/Standard.ovfx
  Resources/Engine/Shaders/Unlit.ovfx
  Sources/Overload/OvCore/src/OvCore/Rendering/ShadowRenderPass.cpp
  Sources/Overload/OvCore/src/OvCore/Resources/Material.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/MaterialEditor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/OutlineRenderFeature.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
  Sources/Overload/OvRendering/include/OvRendering/Data/Material.h
  Sources/Overload/OvRendering/include/OvRendering/Entities/Drawable.h
  Sources/Overload/OvRendering/include/OvRendering/Resources/Shader.h
  Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp
  Sources/Overload/OvRendering/src/OvRendering/Data/Material.cpp
  Sources/Overload/OvRendering/src/OvRendering/Features/DebugShapeRenderFeature.cpp
  Sources/Overload/OvRendering/src/OvRendering/HAL/OpenGL/GLBackend.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Loaders/ShaderLoader.cpp
  Sources/Overload/OvRendering/src/OvRendering/Resources/Shader.cpp
Labels: Graphics

#547 Cleaned up project hub and asset browser
  Sources/Overload/OvCore/include/OvCore/ResourceManagement/AResourceManager.h
  Sources/Overload/OvCore/include/OvCore/ResourceManagement/AResourceManager.inl
  Sources/Overload/OvCore/include/OvCore/Scripting/Common/TScriptEngine.h
  Sources/Overload/OvCore/include/OvCore/Scripting/Lua/LuaScriptEngine.h
  Sources/Overload/OvCore/src/OvCore/SceneSystem/SceneManager.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Lua/LuaScriptEngine.cpp
  Sources/Overload/OvCore/src/OvCore/Scripting/Null/NullScriptEngine.cpp
  Sources/Overload/OvEditor/include/OvEditor/Core/Application.h
  Sources/Overload/OvEditor/include/OvEditor/Core/Context.h
  Sources/Overload/OvEditor/include/OvEditor/Core/EditorActions.h
  Sources/Overload/OvEditor/include/OvEditor/Core/ProjectHub.h
  Sources/Overload/OvEditor/include/OvEditor/Panels/AssetBrowser.h
  Sources/Overload/OvEditor/include/OvEditor/Utils/FileSystem.h
  Sources/Overload/OvEditor/include/OvEditor/Utils/ProjectManagement.h
  Sources/Overload/OvEditor/src/OvEditor/Core/Application.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/Context.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/Editor.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Core/ProjectHub.cpp
  Sources/Overload/OvEditor/src/OvEditor/Main.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
  Sources/Overload/OvEditor/src/OvEditor/Utils/ProjectManagement.cpp
  Sources/Overload/OvGame/include/OvGame/Core/Context.h
  Sources/Overload/OvGame/src/OvGame/Core/Context.cpp
Labels: QoL, Editor, Project Configuration

#551 Various fixes and cleanup for post-process pass
  Resources/Engine/Shaders/PostProcess/Bloom.ovfx
  Resources/Engine/Shaders/PostProcess/BloomDownsampling.ovfx
  Resources/Engine/Shaders/PostProcess/BloomUpsampling.ovfx
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/AutoExposureEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcess/BloomEffect.h
  Sources/Overload/OvCore/include/OvCore/Rendering/PostProcessRenderPass.h
  Sources/Overload/OvCore/src/OvCore/ECS/Components/CPostProcessStack.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcess/AutoExposureEffect.cpp
  Sources/Overload/OvCore/src/OvCore/Rendering/PostProcessRenderPass.cpp
  Sources/Overload/OvRendering/src/OvRendering/Context/Driver.cpp
Labels: Graphics, Cleanup

#557 Fixed releasing mouse right click while in game unlocks the cursor
  Sources/Overload/OvEditor/src/OvEditor/Core/CameraController.cpp
Labels: Critical, Editor

#558 Cleaned up inspector code and fixed renaming bug
  Sources/Overload/OvEditor/include/OvEditor/Panels/Inspector.h
  Sources/Overload/OvEditor/src/OvEditor/Core/EditorActions.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/Inspector.cpp
Labels: Editor, Refactoring

#559 Bumped Overload version to 1.5
  VERSION.txt
Labels: Project Configuration

#560 Updated README for 1.5
  README.md
Labels: Documentation

#577 Stateless texture unit binding
  Sources/Overload/OvRendering/src/OvRendering/HAL/OpenGL/GLTextureHandle.cpp
Labels: Optimization, Graphics

#578 Fixed picking pass to only draw when the scene view is hovered
  Sources/Overload/OvEditor/include/OvEditor/Core/CameraController.h
  Sources/Overload/OvEditor/src/OvEditor/Core/CameraController.cpp
  Sources/Overload/OvEditor/src/OvEditor/Panels/SceneView.cpp
  Sources/Overload/OvEditor/src/OvEditor/Rendering/PickingRenderPass.cpp
Labels: Editor, Graphics
